"""
AI analysis using Groq API.
Sends alert details + log lines to Llama 3.1.
Returns root cause analysis and a draft runbook.
"""
from dataclasses import dataclass
from openai import OpenAI
from agent import config
from agent.prometheus_client import Alert


@dataclass
class Analysis:
    root_cause:      str
    confidence:      str    # high / medium / low
    immediate_steps: list[str]
    runbook_markdown: str


def analyze(alert: Alert, logs: str) -> Analysis:
    """
    Send alert + logs to Groq AI.
    Returns structured analysis with root cause and runbook.
    """
    if not config.GROQ_API_KEY:
        return _rule_based_analysis(alert, logs)

    try:
        client = OpenAI(
            api_key=config.GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1",
        )

        prompt = _build_prompt(alert, logs)
        response = client.chat.completions.create(
            model=config.AI_MODEL,
            max_tokens=config.AI_MAX_TOKENS,
            messages=[{"role": "user", "content": prompt}],
        )

        raw = response.choices[0].message.content
        return _parse_response(alert, raw)

    except Exception as e:
        print(f"  [WARN] AI analysis failed: {e} — using rule-based fallback")
        return _rule_based_analysis(alert, logs)


def _build_prompt(alert: Alert, logs: str) -> str:
    return f"""You are a senior Site Reliability Engineer (SRE) analysing a Kubernetes alert.

ALERT DETAILS
Name:        {alert.name}
Severity:    {alert.severity}
Namespace:   {alert.namespace}
Pod:         {alert.pod}
Summary:     {alert.summary}
Description: {alert.description}
Started at:  {alert.starts_at}

RECENT LOG LINES (last {config.LOKI_LOG_LINES} lines)
```
{logs}
```

TASK
Analyse the alert and logs. Respond in this exact format:

## Root Cause
[2-3 sentences explaining what is wrong and why, based on the logs]

## Confidence
[high / medium / low — how certain are you based on available evidence]

## Immediate Actions
1. [First thing to do right now]
2. [Second thing]
3. [Third thing if needed]

## Draft Runbook

### Alert: {alert.name}

**Severity:** {alert.severity}
**Affects:** {alert.namespace}/{alert.pod}

### What happened
[Plain English description of the incident]

### Root cause
[Technical explanation]

### How to fix it

#### Step 1 — Verify the issue
```bash
kubectl get pods -n {alert.namespace}
kubectl describe pod {alert.pod} -n {alert.namespace}
kubectl logs {alert.pod} -n {alert.namespace} --tail=50
```

#### Step 2 — [Next action based on root cause]
```bash
[Command]
```

#### Step 3 — [Further action]
```bash
[Command]
```

### How to verify it is fixed
[What to check to confirm the issue is resolved]

### Prevention
[1-2 sentences on how to prevent this in future]

### Related alerts
- [Any related alert names]

---
*Generated by Agentic AIOps · {alert.starts_at}*

Rules:
- Be specific — use the actual namespace, pod name, and error from the logs
- Commands must be real kubectl/azure CLI commands
- Keep the runbook under 400 words
- If you cannot determine root cause from the logs, say so clearly"""


def _parse_response(alert: Alert, raw: str) -> Analysis:
    """Parse the AI response into structured fields."""
    sections = raw.split("##")

    root_cause = ""
    confidence = "medium"
    immediate_steps = []
    runbook = raw  # full response becomes the runbook

    for section in sections:
        s = section.strip()
        if s.startswith("Root Cause"):
            root_cause = s.replace("Root Cause", "").strip()
        elif s.startswith("Confidence"):
            conf_text = s.replace("Confidence", "").strip().lower()
            if "high" in conf_text:
                confidence = "high"
            elif "low" in conf_text:
                confidence = "low"
        elif s.startswith("Immediate Actions"):
            lines = s.replace("Immediate Actions", "").strip().split("\n")
            immediate_steps = [
                l.lstrip("0123456789.- ").strip()
                for l in lines if l.strip()
            ]

    # Extract just the runbook section
    if "## Draft Runbook" in raw:
        runbook = raw.split("## Draft Runbook")[1].strip()

    return Analysis(
        root_cause=root_cause or "Could not determine root cause from available logs.",
        confidence=confidence,
        immediate_steps=immediate_steps or ["Check pod logs", "Describe pod", "Check events"],
        runbook_markdown=runbook,
    )


def _rule_based_analysis(alert: Alert, logs: str) -> Analysis:
    """Fallback when AI is unavailable."""
    name = alert.name.lower()

    if "crashloop" in name or "crash" in name:
        return Analysis(
            root_cause="Pod is repeatedly crashing. Check logs for exit code and error message.",
            confidence="medium",
            immediate_steps=[
                f"kubectl logs {alert.pod} -n {alert.namespace} --previous",
                f"kubectl describe pod {alert.pod} -n {alert.namespace}",
                "Check for missing environment variables or misconfigured secrets",
            ],
            runbook_markdown=_crash_runbook(alert),
        )
    elif "imagepull" in name or "image" in name:
        return Analysis(
            root_cause="Kubernetes cannot pull the container image. "
                       "Likely an authentication issue with the container registry.",
            confidence="high",
            immediate_steps=[
                "Check if the ACR pull secret exists in the namespace",
                f"kubectl get secret acr-secret -n {alert.namespace}",
                "Recreate the ACR pull secret if missing",
            ],
            runbook_markdown=_imagepull_runbook(alert),
        )
    else:
        return Analysis(
            root_cause="Unknown root cause — manual investigation required.",
            confidence="low",
            immediate_steps=[
                f"kubectl describe pod {alert.pod} -n {alert.namespace}",
                f"kubectl logs {alert.pod} -n {alert.namespace} --tail=100",
                "Check recent deployments and config changes",
            ],
            runbook_markdown=_generic_runbook(alert),
        )


def _crash_runbook(alert: Alert) -> str:
    return f"""### Alert: {alert.name}

**Severity:** {alert.severity}
**Affects:** {alert.namespace}/{alert.pod}

### What happened
The pod {alert.pod} in namespace {alert.namespace} is crash looping —
it starts, crashes, and Kubernetes keeps restarting it.

### How to investigate

```bash
# Check current state
kubectl get pods -n {alert.namespace}

# Read the crash logs from the previous (crashed) container
kubectl logs {alert.pod} -n {alert.namespace} --previous

# Check events for more context
kubectl describe pod {alert.pod} -n {alert.namespace}
```

### Common causes and fixes

**Missing environment variable or secret:**
```bash
kubectl get secret -n {alert.namespace}
kubectl describe pod {alert.pod} -n {alert.namespace} | grep -A5 Environment
```

**OOMKilled (out of memory):**
```bash
# Check if exit code is 137
kubectl describe pod {alert.pod} -n {alert.namespace} | grep "Exit Code"
# If yes, increase memory limits in the deployment manifest
```

**Application error on startup:**
Check logs for ERROR or FATAL lines and fix the underlying application issue.

### Prevention
Set proper resource requests/limits and use readiness probes to catch
startup failures before they become crash loops.

---
*Generated by Agentic AIOps · {alert.starts_at}*"""


def _imagepull_runbook(alert: Alert) -> str:
    return f"""### Alert: {alert.name}

**Severity:** {alert.severity}
**Affects:** {alert.namespace}/{alert.pod}

### What happened
Kubernetes cannot pull the container image.
Reason: ImagePullBackOff — usually an authentication failure with the registry.

### How to fix

```bash
# Check if ACR pull secret exists
kubectl get secret acr-secret -n {alert.namespace}

# If missing, recreate it
ACR_PASSWORD=$(az acr credential show \\
  --name devopsplatformacr \\
  --query passwords[0].value -o tsv)

kubectl create secret docker-registry acr-secret \\
  --namespace {alert.namespace} \\
  --docker-server=devopsplatformacr.azurecr.io \\
  --docker-username=devopsplatformacr \\
  --docker-password="$ACR_PASSWORD"

# Restart the deployment to trigger a fresh pull
kubectl rollout restart deployment -n {alert.namespace}
```

### Verify fix
```bash
kubectl get pods -n {alert.namespace} -w
# Should show Running within 60 seconds
```

---
*Generated by Agentic AIOps · {alert.starts_at}*"""


def _generic_runbook(alert: Alert) -> str:
    return f"""### Alert: {alert.name}

**Severity:** {alert.severity}
**Affects:** {alert.namespace}/{alert.pod}

### Investigation steps

```bash
kubectl get pods -n {alert.namespace}
kubectl describe pod {alert.pod} -n {alert.namespace}
kubectl logs {alert.pod} -n {alert.namespace} --tail=100
kubectl get events -n {alert.namespace} --sort-by='.lastTimestamp'
```

### Notes
Root cause could not be determined automatically.
Manual investigation required.

---
*Generated by Agentic AIOps · {alert.starts_at}*"""